#cloud-config
hostname: ${HOSTNAME}
manage_etc_hosts: false
package_upgrade: true
fqdn: ${HOSTNAME}.kludge.city
chpasswd:
  expire: False
packages:
  - qemu-guest-agent
  - vim
snap:
  commands:
    - snap install microk8s --classic
users:
  - default
  - name: ${CI_USER}
    plain_text_passwd: ${CI_PASSWORD}
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
