#!/bin/bash

source ${ROOTDIR}/.env
source ${ROOTDIR}/lib/utils.sh
VERSION=0.0.1
DEFAULT_CONFIG_DIR=~/.config/homelab

function parse_args() {
    while [[ $# -gt 0 ]]; do
        ARG="$1"
        case $ARG in
        setup)
            COMMAND="${COMMAND:-do_setup}"
            shift
            ;;
        teardown)
            COMMAND="${COMMAND:-do_teardown}"
            shift
            ;;
        kapply)
            COMMAND="${COMMAND:-do_kapply}"
            shift
            ;;
        -c|--config-dir)
            CONFIG_DIR="$2"
            shift 2
            ;;
        *)
            shift
            ;;
        esac
    done

    if [ -z ${COMMAND} ]; then
        print_usage
    fi

    CONFIG_DIR=${CONFIG_DIR:-$DEFAULT_CONFIG_DIR}
    if [ ! -d ${CONFIG_DIR} ]; then
        print_usage
    fi
}

function do_setup() {
    # Copy installation files to the Proxmox server
    rsync -arvzP \
        ${CI_SSH_KEY_PATH}/${CI_PUBLIC_KEY_FILE} \
        ${CI_SSH_KEY_PATH}/${CI_PRIVATE_KEY_FILE} \
        ${CONFIG_DIR}/proxmox/ \
        ${ROOTDIR}/.env \
        ${ROOTDIR}/cmd/setup/ \
        ${PROXMOX_USER}@${PROXMOX_HOST}:${SERVER_ROOT_DIR}

    # Execute command on Proxmox server
    ssh ${PROXMOX_USER}@${PROXMOX_HOST} "${SERVER_ROOT_DIR}/proxmox-setup.sh; rm -rf ${SERVER_ROOT_DIR}"

    # Generate K8s dashboard certs on K8s master
    K8S_MASTER="$(get_k8s_master_hostname)"
    ssh -o 'StrictHostKeyChecking no' ${CI_USER}@${K8S_MASTER}.${SEARCH_DOMAIN} 'bash -s' < ${ROOTDIR}/cmd/setup/generate-k8s-dashboard-certs.sh

    # Enable microk8s plugins
    ssh -o 'StrictHostKeyChecking no' ${CI_USER}@${K8S_MASTER}.${SEARCH_DOMAIN} "microk8s enable dashboard dns ingress metallb:${K8S_LB_IP_RANGE}"
}

function do_teardown() {
    # Copy installation files to the remote server
    rsync -arvzP \
        ${CONFIG_DIR}/proxmox/ \
        ${ROOTDIR}/.env \
        ${ROOTDIR}/cmd/teardown/ \
        ${PROXMOX_USER}@${PROXMOX_HOST}:${SERVER_ROOT_DIR}

    # Execute command on Proxmos server
    ssh ${PROXMOX_USER}@${PROXMOX_HOST} "${SERVER_ROOT_DIR}/proxmox-teardown.sh; rm -rf ${SERVER_ROOT_DIR}"
}

function do_kapply() {
    K8S_MASTER="$(get_k8s_master_hostname)"

    # Copy k8s files to the remote server
    rsync -arvzP \
        ${CONFIG_DIR}/k8s/ \
        ${CI_USER}@${K8S_MASTER}:${SERVER_ROOT_DIR}

    # Apply k8s files on the remote server
    ssh -o 'StrictHostKeyChecking no' ${CI_USER}@${K8S_MASTER}.${SEARCH_DOMAIN} "cd ${SERVER_ROOT_DIR}; microk8s kubectl apply -f . -R"
}

function print_usage() {
    echo "Homelab v${VERSION}"
    echo "Usage: $(basename "$0") [setup|teardown]" 
    exit 1
}

parse_args $@
$COMMAND 
